import { SlashCommandBuilder, PermissionFlagsBits as P } from 'discord.js';
import { templates } from './content.js';
const command=(name,description)=>new SlashCommandBuilder().setName(name).setDescription(description).setDMPermission(false);
export const commands=[
  command('setup','Set up private modmail staff channels and roles').setDefaultMemberPermissions(P.Administrator),
  command('panel','Post or update the Customer Assistance DM panel').setDefaultMemberPermissions(P.ManageGuild)
    .addAttachmentOption(o=>o.setName('banner').setDescription('Optional PNG, JPEG, GIF or WebP banner; max 8 MB')),
  command('helpdesk','Explain how to contact staff through modmail'),
  command('modmail','Manage a private modmail conversation')
    .addSubcommand(s=>s.setName('inbox').setDescription('View the live staff queue')
      .addStringOption(o=>o.setName('filter').setDescription('Queue filter').addChoices(...['all','unclaimed','mine','overdue'].map(v=>({name:v,value:v}))))
      .addIntegerOption(o=>o.setName('page').setDescription('Page number').setMinValue(1).setMaxValue(10000)))
    .addSubcommand(s=>s.setName('priority').setDescription('Set this conversation priority')
      .addStringOption(o=>o.setName('level').setDescription('Priority').setRequired(true).addChoices(...['low','normal','high','urgent'].map(v=>({name:v,value:v})))))
    .addSubcommand(s=>s.setName('assign').setDescription('Assign this conversation to a staff member (admin)')
      .addUserOption(o=>o.setName('user').setDescription('Staff member').setRequired(true)))
    .addSubcommand(s=>s.setName('tag').setDescription('Add or remove a searchable conversation label')
      .addStringOption(o=>o.setName('label').setDescription('Lowercase letters, numbers and hyphens; max 24 characters').setRequired(true).setMaxLength(24))
      .addBooleanOption(o=>o.setName('remove').setDescription('Remove this label instead of adding it')))
    .addSubcommand(s=>s.setName('search').setDescription('Search recorded messages and tags you are authorized to access')
      .addStringOption(o=>o.setName('query').setDescription('Text or tag to find').setRequired(true).setMinLength(2).setMaxLength(100))
      .addIntegerOption(o=>o.setName('page').setDescription('Page number').setMinValue(1).setMaxValue(10000)))
    .addSubcommand(s=>s.setName('history').setDescription('List a member’s past conversations you can access')
      .addUserOption(o=>o.setName('user').setDescription('Member').setRequired(true))
      .addIntegerOption(o=>o.setName('page').setDescription('Page number').setMinValue(1).setMaxValue(10000)))
    .addSubcommand(s=>s.setName('stats').setDescription('Response times, queue health and satisfaction'))
    .addSubcommand(s=>s.setName('deliveries').setDescription('Show recent message delivery status in this conversation'))
    .addSubcommand(s=>s.setName('controls').setDescription('Show quick reply, note, claim, close and details controls'))
    .addSubcommand(s=>s.setName('settings').setDescription('Set the staff response target (admin)')
      .addIntegerOption(o=>o.setName('response_minutes').setDescription('Internal target in minutes; not a public promise').setMinValue(5).setMaxValue(10080).setRequired(true))
      .addBooleanOption(o=>o.setName('feedback').setDescription('Send optional satisfaction surveys when conversations close')))
    .addSubcommand(s=>s.setName('reply').setDescription('Send an explicit reply to the member via bot DM')
      .addStringOption(o=>o.setName('message').setDescription('Message to send to the member').setMaxLength(3500))
      .addAttachmentOption(o=>o.setName('attachment').setDescription('Optional attachment (forwarded as a Discord link)')))
    .addSubcommand(s=>s.setName('template').setDescription('Send a prepared reply to the member')
      .addStringOption(o=>o.setName('name').setDescription('Prepared reply').setRequired(true).addChoices(...Object.keys(templates).map(v=>({name:v,value:v})))))
    .addSubcommand(s=>s.setName('note').setDescription('Record a staff-only note; never sent to the member')
      .addStringOption(o=>o.setName('message').setDescription('Internal note').setMaxLength(3500).setRequired(true)))
    .addSubcommand(s=>s.setName('claim').setDescription('Assign this conversation to yourself'))
    .addSubcommand(s=>s.setName('unclaim').setDescription('Release your claim'))
    .addSubcommand(s=>s.setName('escalate').setDescription('Restrict the conversation to admins'))
    .addSubcommand(s=>s.setName('close').setDescription('Archive and close; the next member DM starts a new conversation')
      .addStringOption(o=>o.setName('reason').setDescription('Closure reason shared with the member').setMaxLength(1000).setRequired(true)))
    .addSubcommand(s=>s.setName('transcript').setDescription('Download the staff-only conversation record'))
    .addSubcommand(s=>s.setName('info').setDescription('Show member, assignment, and status'))
    .addSubcommand(s=>s.setName('block').setDescription('Block incoming modmail from a member (admin)')
      .addUserOption(o=>o.setName('user').setDescription('Member to block').setRequired(true)))
    .addSubcommand(s=>s.setName('unblock').setDescription('Restore incoming modmail for a member (admin)')
      .addUserOption(o=>o.setName('user').setDescription('Member to unblock').setRequired(true)))
].map(c=>c.toJSON());
